version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/react-speedgame
    ports:
      - 3010:3000
    image: app:react-speedgame
    container_name: speedgame_container
    command: npm start